feat: Pass full state to persist transforms
ctrlplusb/easy-peasy pull request #816
Opened 2023-02-03 00:04 UTC by damassi

Noticed a slight divergence from the `redux-persist` [transform api](https://github.com/rt2zz/redux-persist/blob/master/src/createTransform.ts#L26-L33), where there they pass the full state along with the `in` and `out` calls. This also aligns with the api as seen in `create-transform` code in the easy-peasy [codebase](https://github.com/ctrlplusb/easy-peasy/blob/master/src/create-transform.js#L17-L24). 

Now the api is: 
```tsx
in(state, key, fullState) => { ... }
out(state, key, fullState) => { ... }
```

2023-04-12 17:21 UTC, no-stack-dub-sack requested changes
@damassi this looks good to me - would you mind taking a look at the persist tests and seeing if it makes sense to add or modify any existing tests to reflect the new API?

2023-04-12 17:22 UTC, damassi commented
Sure thing, I'll do this now.

2023-04-12 17:54 UTC, damassi commented
@no-stack-dub-sack Updated tests to reflect the additional parameter being passed into the transform. Let me know if this is sufficient!

2023-04-18 01:37 UTC, no-stack-dub-sack approved these changes

2023-04-18 01:37 UTC, no-stack-dub-sack commented
Thanks @damassi! LGTM!

2023-04-18 01:37 UTC, merged